"""empty message

Revision ID: dd6b86c7a0df
Revises: 34a1d77250a2
Create Date: 2018-12-01 00:32:03.752775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6b86c7a0df'
down_revision = '34a1d77250a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_logs', sa.Column('log_link', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_logs', 'log_link')
    # ### end Alembic commands ###
